management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,beans
spring:
  datasource:
    url: jdbc:mysql://47.102.220.5:3306/kyrieboot20210225?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kyrie
    password: kyrie
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.102.220.5
    port: 6379
    password:
    timeout: 5000
logging:
  config: classpath:log4j2-spring.xml
